import Head from 'next/head'
import Experience from '../components/Experience'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import {useState} from "react"
import { motion } from "framer-motion";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);


  return (
    <motion.div 
   initial={{y:-100}}
    animate={{y:0}}
    transition={{duration:1 }}
    className={darkMode? 'dark': ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gradient-to-br from-white to-black/10 dark:bg-gradient-to-r dark:from-[#2B2B2B] dark:to-[#000] duration-500 ease-linear px-10 w-screen'>
        <section className="min-h-screen w-full">
          <Header darkMode={darkMode} setDarkMode={setDarkMode} />
          <Hero/>
          <section className="flex bg-gray-100 
          dark:bg-black/20
           mt-10 rounded-lg shadow-xl flex-col items-center justify-center space-y-10">
          <Experience/>
          <Skills/>
          <Projects/>
          </section>
          <Footer/>
        </section>
      </main>
    </motion.div>
  )
}
