import Head from 'next/head'
import Experience from '../components/Experience'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import { useEffect, useState } from "react"
import { motion } from "framer-motion";
import axios from "axios";
export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  const getPersonalData = () => {
    // headers
    const config = {
      headers: {
        'Content-Type': 'application/json',
        'Allow-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET,PUT,POST,DELETE,PATCH,OPTIONS',
      },
    };
    const data = axios.get("https://prajwalladkatportfolio.vercel.app/api/getInfo", config)
    .then((res) => {
      console.log(res.data);
    }
    )
   
  }

  useEffect(() => {
    getPersonalData();
  }, [])

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5 }}
      className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gradient-to-br from-white to-black/10 dark:bg-gradient-to-r dark:from-[#2B2B2B] dark:to-[#000] duration-500 ease-linear px-0 lg:px-10 w-screen'>
        <section className="min-h-screen w-full">
          <Header darkMode={darkMode} setDarkMode={setDarkMode} />
          <Hero />
          <section className="flex bg-gray-100 
          dark:bg-black/20
           mt-10 rounded-lg shadow-xl flex-col items-center justify-center space-y-10">
            <Experience />
            <Skills />
            <Projects />
          </section>
          <Footer />
        </section>
      </main>
    </motion.div>
  )
}
